# Generated by Django 4.1.4 on 2022-12-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfmodel',
            name='file',
            field=models.FileField(upload_to='pdfs'),
        ),
    ]
